codecov:
  strict_yaml_branch: master
  notify:
    delay: 5
coverage:
  range: [80, 100]
  notify:
    email:
      default:
        to: ehmicky@gmail.com
        threshold: 100
        branches: null
        layout: reach,diff,flags,files
        only_pulls: false
        flags: null
        paths: null
  parsers:
    javascript:
      enable_partials: true
comment:
  layout: reach,diff,flags,files
