language: node_js
node_js:
  - 11
os:
  - linux
script: npm run ci-test
cache: npm
# This merges all LCOV files into one before sending to Coveralls, allowing
# code coverage percentage to include OS/environment-specific coverage.
env:
  global: COVERALLS_PARALLEL=true
notifications:
  webhooks:
    - https://coveralls.io/webhook
    - https://www.travisbuddy.com?only=failed,errored
  email: false
travisBuddy:
  insertMode: update
